### ISSUE TITLE
Hackage documentation missing

### ISSUE THREAD

**Issue by expipiplus1** [adamgundry/uom-plugin#18]
The build has been pending for quite a while.

I've never found the Hackage documentation generator to be too reliable. This script from Linear makes it dead easy to generate and upload docs: https://github.com/ekmett/lens/blob/master/scripts/hackage-docs.sh

**Comment by adamgundry** [comment]
It turns out that Hackage has now successfully generated the docs. But thanks for the pointer to the script, I'll try to make sure that docs get put up more promptly in future.
