### ISSUE TITLE
A stack resolver that matches one of the tested GHC versions

### ISSUE THREAD

**Issue by philderbeast** [adamgundry/uom-plugin#38]
We're testing with ghc `7.10.3`, `8.0.1` & `8.0.2`.

https://github.com/adamgundry/uom-plugin/blob/107fdd7bcdb22e2afef5d868e7b902f49690dd30/uom-plugin/uom-plugin.cabal#L16-L19

Can we pick a stack resolver that matches one of these versions please?

https://github.com/adamgundry/uom-plugin/blob/107fdd7bcdb22e2afef5d868e7b902f49690dd30/uom-plugin/stack.yaml#L1

[Latest LTS per GHC version](https://www.stackage.org/)
* LTS 11.7 for GHC 8.2.2, published a week ago
* LTS 9.21 for GHC 8.0.2, published 4 months ago
* LTS 7.24 for GHC 8.0.1, published 11 months ago
* LTS 6.35 for GHC 7.10.3, published 11 months ago
* LTS 3.22 for GHC 7.10.2, published 2 years ago

**Comment by philderbeast** [comment]
I see that we're not testing with ghc `8.0.1` but we are testing with ghc `8.2.1`.

https://github.com/adamgundry/uom-plugin/blob/107fdd7bcdb22e2afef5d868e7b902f49690dd30/.travis.yml#L29-L37

**Comment by adamgundry** [comment]
Resolved by 78a4fdf
