### ISSUE TITLE
Unable to define derived units from compound units

### ISSUE THREAD

**Issue by expipiplus1** [adamgundry/uom-plugin#4]
Trying to declare Liters for example:

```
[u| l = 0.001 m^3 |]
```

This seems to fail initially here https://github.com/adamgundry/uom-plugin/blob/master/uom-plugin/src/Data/UnitsOfMeasure/TH.hs#L131 when the other constructors of UnitExp aren't matched.

**Comment by adamgundry** [comment]
There's a more fundamental issue here: at the moment the type-level hackery for automatic conversion inference relies on the fact that conversion ratios are defined only between base units. I'll have to take another look to see if this restriction can be relaxed.

**Comment by adamgundry** [comment]
This turned out to be much easier than I thought. Of course, it's possible that it is broken in some way that I can't currently see, but it appears to permit basic conversions involving derived compound units.
