### ISSUE TITLE
haddock: internal error: renameType: HsSpliceTy

### ISSUE THREAD

**Issue by philderbeast** [adamgundry/uom-plugin#57]
I encountered a problem with haddock using the uom-plugin even when there are no haddock comments! @adamgundry I mentioned this to you at ZuriHac and now I have a small reproduction of the problem. This could be https://github.com/haskell/haddock/issues/233 or https://github.com/haskell/haddock/issues/574.

```
> stack haddock uom-haddock
...
haddock: internal error: renameType: HsSpliceTy
CallStack (from HasCallStack):
  error, called at utils/haddock/haddock-api/src/Haddock/Interface/Rename.hs:267:30 in main:Haddock.Interface.Rename
```

I've left this here so we can investigate it further.

I hope we can get the version of haddock that is paired with ghc-8.2.2 patched and get the uom-plugin working with later ghc versions.

https://github.com/sjakobi/haddock/commit/af7a4410a17a4f0d37d1cab6fcd14b0c305c8ef3

**Comment by philderbeast** [comment]
Here's the one source file;

```
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}

{-# OPTIONS_GHC -fplugin Data.UnitsOfMeasure.Plugin #-}
{-# OPTIONS_GHC -fno-warn-orphans #-}

module Units.Angle (Angle(..)) where

import Data.UnitsOfMeasure (u, convert)
import Data.UnitsOfMeasure.Internal (Quantity(..))
import Data.UnitsOfMeasure.Convert (Convertible)

[u| deg |]

class Angle a where
    fromQuantity :: Convertible u [u| deg |] => Quantity Double u -> a
    toQuantity :: Convertible u [u| deg |] => a -> Quantity Double u

instance Convertible u [u| deg |] => Angle (Quantity Double u) where
    fromQuantity = convert
    toQuantity = convert
```

**Comment by adamgundry** [comment]
Indeed, it sounds like Haddock has a bug with TH splices in types. I guess our options are to write out the spliced-in types by hand, or wait for a fixed Haddock...

**Comment by philderbeast** [comment]
This is no longer a problem when `uom-plugin` is built with ghc versions `8.0.2, 8.2.2 and 8.4.4`.

```
> stack haddock --stack-yaml=stack-8.0.2.yaml
> stack haddock --stack-yaml=stack-8.2.2.yaml
> stack haddock --stack-yaml=stack-8.4.4.yaml
```
