### ISSUE TITLE
Instance of Read for quantities

### ISSUE THREAD

**Issue by expipiplus1** [adamgundry/uom-plugin#7]
It would be nice to have an instance of Read for quantities. At the least I suppose this should be the partial inverse of Show. A really nice thing to have would be for it to parse equivalent compound units without a problem.

**Comment by adamgundry** [comment]
That's a good idea, thanks. I guess the right thing is to implement a parser for an existential wrapper around `Quantity` that determines the units at runtime, then the `Read (Quantity a u)` instance can be defined to check that the units have equivalent normal forms. For example, this would allow `read "[u| 5 m s^-1 |]" :: Quantity a [u| m/s |]`. It wouldn't cover unit synonyms or conversions, however.
