### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by adamgundry** [adamgundry/uom-plugin#79]
It looks like the removal of type family application flattening in GHC 9.2 means the plugin should start to work again. I have a prototype on the `ghc-9.2` branch that passes the existing testsuite. I'll try to produce a version that is compatible with 9.2.

I'm wondering about dropping support for some or all old GHC versions, because it would be simpler not to bother with so many backwards-compatibility hacks. @philderbeast do you have an opinion on which GHC versions should be supported?

**Comment by philderbeast** [comment]
That's great @adamgundry.

For the next version let's support only `impl(ghc >= 9.2)`. For `impl(ghc <= 8.2.2)` there's always `uom-plugin-0.3.0.0` up on hackage. We could note that in the readme. If we can find a way to fill in the missing GHC version range then we could cut another release later on when we're able.

**Comment by adamgundry** [comment]
Fixed by #93.
